"""tamo.derive — 収集済み履歴からの「還流」機能。

SpecStoryから学んだ2つの価値を、tamoの設計原則（決定論・出所ID付き）で再実装する:

1. mirror — セッションをプロジェクト内の .tamo/history/*.md にミラーする。
   SpecStoryの .specstory/history と同じく「gitにコミットでき、PRでAIとの
   検討経緯をレビューでき、grepできる」形。tamoのDBは正、mirrorは常に再生成
   可能なビュー（手編集しない前提）。--redact で秘密情報を除去してから書く。

2. rules — 会話履歴から「決定事項・制約・エラーと対処」を規則ベースで抽出し、
   CLAUDE.md 等に還流できる導出ルール文書を作る。SpecStoryのDerived Rules /
   Lore（履歴を証拠付きスキルに精製）に相当するが、LLMを使わず決定論。
   各行に ⟨e:xxxx⟩ の出所IDが付くので、疑わしければ原文に遡れる。
   マーカー <!-- tamo:rules:begin/end --> の間だけを冪等に書き換える。
"""
from __future__ import annotations

import re
from pathlib import Path

from .optimize import dedup_events, extract_salience
from .redact import merge_counts, redact_text
from .schema import blocks_text
from .store import Store
from .util import strip_noise

RULES_BEGIN = "<!-- tamo:rules:begin (auto-generated by `tamo rules --write`; edits inside will be overwritten) -->"
RULES_END = "<!-- tamo:rules:end -->"


# ------------------------------------------------------------------ 共通

def _match_session(store: Store, s: dict, needle: str | None) -> bool:
    """--project フィルタ: session_key/タイトル/先頭イベントのlocatorに部分一致。"""
    if not needle:
        return True
    hay = f"{s['session_key']} {s.get('title') or ''}"
    if needle in hay:
        return True
    row = store.con.execute(
        "SELECT ces FROM events WHERE session_key=? ORDER BY seq LIMIT 1",
        (s["session_key"],)).fetchone()
    if not row:
        return False
    import json as _json
    return needle in str(_json.loads(row[0]).get("locator") or "")


def _slug(text: str, fallback: str) -> str:
    t = re.sub(r"[^\w\u3040-\u30ff\u3400-\u9fff-]+", "-", (text or fallback)).strip("-")
    return (t[:60] or fallback).rstrip("-")


# ------------------------------------------------------------------ mirror

def mirror_sessions(store: Store, out_dir: Path, project: str | None = None,
                    redact: bool = False) -> dict:
    """セッションごとの Markdown を out_dir に書く（決定論・毎回全文再生成）。"""
    out_dir.mkdir(parents=True, exist_ok=True)
    written, red_counts = [], {}
    for s in store.list_sessions(limit=100000):
        if not _match_session(store, s, project):
            continue
        events = store.iter_session_events(s["session_key"])
        if not events:
            continue
        lines = [
            f"# {s.get('title') or s['session_key']}",
            "",
            f"- source: `{s['source_kind']}` / session: `{s['session_key']}`",
            f"- span: {s.get('first_ts') or '-'} → {s.get('last_ts') or '-'} / events: {s.get('n_events')}",
            "- generated by `tamo mirror` — 再生成されるので直接編集しない（正はtamoのDB）",
            "",
            "---",
            "",
        ]
        for ev in events:
            text = strip_noise(blocks_text(ev.get("content", [])))
            if not text.strip():
                continue
            head = f"## {ev.get('actor')}"
            if ev.get("kind") not in (None, "message"):
                head += f" ({ev['kind']})"
            head += f" — {ev.get('ts') or '-'} ⟨e:{ev['event_id'][:8]}⟩"
            lines += [head, "", text, ""]
        body = "\n".join(lines)
        if redact:
            body, c = redact_text(body)
            merge_counts(red_counts, c)
        date = (s.get("first_ts") or "")[:10] or "undated"
        name = f"{date}-{_slug(s.get('title') or '', s['session_key'].split(':')[-1])}.md"
        (out_dir / name).write_text(body, encoding="utf-8")
        written.append(name)
    return {"written": len(written), "dir": str(out_dir), "files": written,
            "redacted": red_counts}


# ------------------------------------------------------------------ rules

_SECTIONS = [
    ("decision", "決定事項 (Decisions)"),
    ("constraint", "制約・前提 (Constraints)"),
    ("error_fix", "既知のエラーと対処 (Errors → Fixes)"),
]


def derive_rules(store: Store, project: str | None = None, days: int | None = None,
                 per_section: int = 20) -> str:
    """履歴から導出ルールのMarkdown本文を作る（LLM不使用・出所ID付き）。"""
    events: list[dict] = []
    for s in store.list_sessions(limit=100000):
        if _match_session(store, s, project):
            events.extend(store.iter_session_events(s["session_key"]))
    if days:
        from datetime import datetime, timedelta, timezone

        cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%dT%H:%M:%S")
        events = [e for e in events if not e.get("ts") or str(e["ts"])[:19] >= cutoff]
    events.sort(key=lambda e: (e.get("ts") or "", e.get("seq") or 0))
    events, _ = dedup_events(events)
    sal = extract_salience(events)

    out = ["> tamoが会話履歴から決定論で導出したコンテキスト。各行の ⟨e:xxxx⟩ で原文に遡れる。",
           "> 自動再生成される区間（正は原文イベント）。誤抽出は出力を直さず、抽出規則を直して再生成する。", ""]
    seen: set[str] = set()
    n_rows = 0
    for key, title in _SECTIONS:
        rows = []
        for r in sal.get(key, []):
            norm = re.sub(r"\s+", " ", r["text"]).strip()
            if key == "error_fix" and "→ FIX:" in norm:
                norm = "fix::" + norm.split("→ FIX:", 1)[1].strip()  # 同一FIXは1回だけ
            if norm and norm not in seen:
                seen.add(norm)
                rows.append(r)
        if not rows:
            continue
        out.append(f"### {title}")
        for r in rows[:per_section]:
            out.append(f"- {r['text']}  ⟨e:{r['eid'][:8]}⟩")
            n_rows += 1
        out.append("")
    if n_rows == 0:
        return ""
    return "\n".join(out).rstrip() + "\n"


def write_rules_into(path: Path, rules_md: str) -> str:
    """CLAUDE.md等のマーカー区間だけを冪等に書き換える。無ければ末尾に節を追加。"""
    block = f"{RULES_BEGIN}\n{rules_md}{RULES_END}"
    if path.exists():
        text = path.read_text(encoding="utf-8")
        pat = re.compile(re.escape(RULES_BEGIN) + r".*?" + re.escape(RULES_END), re.S)
        if pat.search(text):
            new = pat.sub(lambda _m: block, text)
            action = "updated"
        else:
            sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
            new = f"{text}{sep}## Derived rules (tamo)\n\n{block}\n"
            action = "appended"
    else:
        new = f"## Derived rules (tamo)\n\n{block}\n"
        action = "created"
    path.write_text(new, encoding="utf-8")
    return action
